package id.my.masdepan.adatin.model

enum class StatusSewa {
    MENUNGGU_PEMBAYARAN,
    SEDANG_DIPROSES,
    SIAP_DIAMBIL,
    SAMPAI_TUJUAN,
    SEDANG_DIANTAR,
    SEDANG_DISEWA,
    MENUNGGU_KONFIRMASI_PEMBATALAN,
    SELESAI,
    DIBATALKAN
}